/*
 * QRZ Logbook API
 *
 * This API provides methods for external programs to interact with the QRZ Logbook using an HTTP REST interface. The QRZ Logbook is a combination free and paid subscription service of QRZ. Some advanced features require a valid subscription while the majority of operations are free to all QRZ members. All users of the QRZ Logbook, regardless of their subscription status, may access, edit, update, and view their complete logs online at the QRZ website.
 *
 * API version: 1.0.0
 * Contact: flloyd@qrz.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qrzlog

// Request struct for Request
type Request struct {
	// A QRZ supplied logbook access key
	KEY string `json:"KEY"`
	// Type of request, i.e. INSERT, DELETE, UPLOAD, etc.
	ACTION string `json:"ACTION"`
	// ADIF formatted input data
	ADIF string `json:"ADIF,omitempty"`
	// Action-specific options
	OPTION string `json:"OPTION,omitempty"`
	// A comma separated list of integer logid values
	LOGIDS string `json:"LOGIDS,omitempty"`
}
